version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./app/index.php:/var/www/index.php
      - ./app/assets:/var/www/assets
    depends_on:
      - php-fpm
      - database
    ports:
      - 80:80
    networks:
      - php-stack

  php-fpm:
    build:
      context: ./php-fpm
    container_name: php-fpm
    restart: unless-stopped
    environment:
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypass
    volumes:
      - ./app/index.php:/var/www/index.php
      - ./app/connection.php:/var/www/connection.php
      - ./app/assets:/var/www/assets
    depends_on:
      - database
    networks:
      - php-stack


  database:
    image: mysql:latest
    container_name: database
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypass
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - php-stack

networks:
  php-stack:
    name: php-stack
